# Use root/example as user/password credentials
version: "3.9"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - "mysql:/var/lib/mysql"
      - "./db:/docker-entrypoint-initdb.d"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} \ --database 'jenny' -e 'SHOW TABLES'",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  backend:
    build: ./backend
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      BACKEND_PORT: ${BACKEND_PORT}
    depends_on:
      db:
        condition: service_healthy

  app:
    build: ./app
    environment:
      TOKEN: ${TOKEN}
      CLIENT_ID: ${CLIENT_ID}
      GUILD_ID: ${GUILD_ID}
      GAME_ANNOUNCEMENT_CHANNEL_ID: ${GAME_ANNOUNCEMENT_CHANNEL_ID}
      BACKEND_DOMAIN: ${BACKEND_DOMAIN}
      BACKEND_PORT: ${BACKEND_PORT}
      SESSION_LENGTH: ${SESSION_LENGTH}
    depends_on:
      - backend

volumes:
  mysql:
    external: false
